# Kling-style delivery notes (Salah, 2026-09-24): the bracket in `The woman (…): "…"` holds only simple,
# performable tone words, the way Kling's own examples do — "(softly, in a surprised tone)",
# "(in a low voice, in a calm tone)". No "then" (a beat map gives each sentence its own bracket), no job
# labels ("the premise"), no metaphors ("the ceiling holding"). Every note the kit uses must be listed here;
# the builder stops on an unmapped one, so a new guest's notes are translated deliberately, never passed through.
TONE = {
 'dry': 'in a dry tone', 'exact': 'in a precise tone', 'plain': 'in a plain tone', 'quietly': 'quietly',
 'plainly': 'plainly', 'even': 'in an even tone', 'the turn': 'in a calm tone',
 'the question, plain': 'in a plain, curious tone', 'pressing': 'in a firm tone', 'moving on, level': 'in a level tone',
 'level': 'in a level tone', 'flat': 'in a flat tone', 'cool correction': 'in a cool tone',
 'with weight, then quieter on the admission': 'in a quiet, serious tone', 'with weight': 'in a serious tone',
 'with the cost held under it': 'in a low, serious tone', 'warm, formal': 'in a warm, formal tone', 'warm and formal, then plain': 'in a warm, formal tone',
 'turning': 'in a calm tone', 'the word placed plainly': 'plainly', 'the summons, plain': 'in a plain tone',
 'the stakes': 'in a serious tone', 'the real question, open': 'in a curious tone', 'the real question': 'in a curious tone',
 'the question landing plain': 'in a plain tone', 'the premise': 'in a level tone', 'the place': 'in a calm tone',
 'the name, placed gently': 'gently', 'the list, even': 'in an even tone', 'the list': 'in an even tone',
 'the image': 'in a warm tone', 'the famous version': 'in a light tone', 'the faintest smile held under': 'in a dry, amused tone',
 'the fact laid down': 'in a plain tone', 'the edge comes in': 'in a cooler tone', 'the cost, held under': 'in a low, serious tone',
 'the charge, plainly': 'plainly', 'the challenge, plain': 'in a firm tone', 'the case, attributed and level': 'in a level tone',
 'the barb': 'in a dry tone', 'surprised, quick': 'in a surprised tone', 'starting to come in, firm but not loud': 'in a firm tone',
 'sobering': 'in a quiet, serious tone', 'slow on the scene': 'in a calm tone', 'short and plain': 'plainly',
 'she lets posterity keep its argument': 'in an even tone', 'setting the scene': 'in a calm tone',
 'reaching for the picture': 'in a warm tone', 'quieter, then personal, the ceiling holding': 'quietly, in a serious tone',
 'quieter, the ceiling holding': 'quietly, in a serious tone', 'quieter, an introduction rather than a flourish': 'quietly',
 'quieter': 'quietly', 'quiet, to her': 'quietly, in a warm tone', 'puzzled, slower': 'in a puzzled tone',
 'putting it together, level': 'in a level tone', 'pressing, curious': 'in a curious tone',
 'pressing lightly': 'in a light, curious tone', 'plainly, so she can refuse it': 'plainly',
 'plainly, not accusing': 'plainly, in a calm tone', 'plain, weight held under': 'in a plain, serious tone',
 'plain, then deliberate': 'in a deliberate tone', 'plain, then asserting': 'in a firm tone',
 'plain, a little cooler on the point': 'in a plain, cool tone', 'plain thanks': 'plainly',
 'plain narration, colder at the end': 'in a cool tone', 'personal, then the decision stated': 'in a low, firm tone',
 'offering the myth': 'in a light tone', 'not letting go, level': 'in a level, firm tone', 'moving on': 'in a level tone',
 'lower': 'in a low voice', 'low, repeating it': 'in a low voice',
 'level, the number left to do the work, dry at the end': 'in a level, dry tone',
 'level, opening more than it closes': 'in a level tone',
 'level, drier toward the end, the principle stated plainly': 'in a level, dry tone',
 'level, and harder on the two names without ever becoming a verdict': 'in a level, firm tone',
 'level, a thin edge': 'in a level, cool tone', 'letting it go': 'in a calm tone', 'leaning in, curious': 'in a curious tone',
 'leading, a smile under it': 'in a light, teasing tone', 'laying it out': 'in a plain tone',
 "giving Rome's view, level": 'in a level tone', 'gently': 'gently', 'flatly': 'flatly', 'flat, no apology': 'in a flat tone',
 'faint pride held under': 'in a quietly proud tone', 'even and factual, dry at the end': 'in an even, dry tone',
 'even and exact': 'in an even tone', 'echoing it, amused': 'in an amused tone', 'dry, with a trace of amusement': 'in a dry, amused tone',
 'dry, low, almost to himself': 'in a low, dry voice', 'dry and exact, a flicker of pride': 'in a dry tone', 'drier': 'in a drier tone',
 'direct, light': 'in a light tone', 'cutting in, cool and exact': 'in a cool, firm tone', 'curious': 'in a curious tone',
 'coolly correcting, the barb held under': 'in a cool tone', 'cooler, exact': 'in a cooler tone', 'cooler': 'in a cooler tone',
 'cool, exact': 'in a cool tone', 'cool narration, colder on the last sentence': 'in a cool tone',
 'cool courtesy': 'in a coolly polite tone', 'cool': 'in a cool tone', 'checking a fact': 'in a plain tone',
 'brightening': 'in a brighter tone', 'amused': 'in an amused tone', 'a small challenge': 'in a lightly challenging tone',
 'a quiet edge': 'in a quiet, cool tone', 'a genuine question': 'in a curious tone', 'a fraction lower': 'in a lower voice',
}
def tone(note):
    k = note.strip()
    if k not in TONE: raise SystemExit(f'STOP — no Kling-style tone for the delivery note "{k}". Add it to Fixed_Assets/tools/tone_map.py.')
    return TONE[k]
