# -*- coding: utf-8 -*-
# Provenance tags, keyed by the ORIGINAL shot id in P1_kit.md (pre-renumber).
# [D] documented - source named. [I] inferred - basis named. [V] voice - no factual claim.
TAGS = {
"P1_004":("D","Augustan-era hostile characterisation of Cleopatra: Cassius Dio 50; Horace, Odes 1.37; Propertius; Plutarch, Life of Antony."),
"P1_005":("D","Last reigning Ptolemaic monarch, 51-30 BC. Caesarion was nominal co-ruler; the lower third says 'Last ruler of Ptolemaic Egypt' for that reason."),
"P1_006":("V",""),
"P1_007":("D","Egypt's grain wealth and absence of a standing legionary force: Roller, *Cleopatra: A Biography*; Chauveau, *Egypt in the Age of Cleopatra*."),
"P1_008":("D","Egyptian exports to Rome - grain above all, with gold, papyrus and glass: Roller; Chauveau."),
"P1_011":("I","Consistent with the documented pattern of Roman financiers lending against Egyptian revenue; the aphorism is hers, the situation is attested."),
"P1_013":("I","Echoes her preceding claim rather than adding one; retagged from [V] because 'they all knew' is an assertion about Roman awareness of Egyptian wealth."),
"P1_014":("D","Ptolemy XII's borrowing from Roman financiers (Rabirius Postumus) to purchase recognition as *amicus et socius populi Romani*, c. 59 BC: Cicero, *Pro Rabirio Postumo*."),
"P1_015":("I","She inherited both the debt and the client relationship; the equation of the two is her framing, not a source's."),
"P1_017":("D","Annexation of Egypt was repeatedly raised at Rome: Cicero, *De Rege Alexandrino*; Suetonius, *Julius* 11."),
"P1_018":("D","The will of Ptolemy XI Alexander II, retained and cited by Rome. VERIFY the exact kinship term before publication - 'cousin' is loose."),
"P1_020":("D","Accession at about eighteen in 51 BC, co-rule with Ptolemy XIII, and the court faction that displaced her: Plutarch; Cassius Dio."),
"P1_021":("D","Expulsion, the raising of forces on the eastern frontier, and the return to the border at Pelusium: Caesar, *Civil War* 3; Plutarch."),
"P1_022":("V",""),
"P1_023":("D","Two centuries of Ptolemaic dynastic killing is the standard characterisation of the later dynasty: Roller; Chauveau."),
"P1_024":("D","Macedonian Greek dynasty; she was the first Ptolemy recorded as learning Egyptian: Plutarch, *Life of Antony* 27."),
"P1_025":("I","Plutarch (*Ant.* 27) says she rarely needed an interpreter and lists the peoples she addressed directly; **the figure 'nine' is a modern enumeration of that list, not Plutarch's own count.** Keep or change the number deliberately."),
"P1_026":("V",""),
"P1_027":("D","Coronation in Egyptian pharaonic form and the role of the priesthood in grain administration: Roller."),
"P1_028":("V",""),
"P1_029":("D","Administrative activity in her own hand - the 'ginesthō' royal subscription - and the papyrological record of grain and temple business: Roller; the papyri."),
"P1_032":("D","Pompey's defeat at Pharsalus, flight to Egypt, and the decision of Ptolemy XIII's court: Caesar, *Civil War* 3; Plutarch, *Life of Pompey* 77-80."),
"P1_033":("D","Pompey killed at the shoreline, head retained and presented to Caesar: Plutarch, *Pompey* 77-80; Cassius Dio 42."),
"P1_035":("D","Caesar's weeping at the presentation of the head is reported in the ancient accounts: Plutarch; Dio 42."),
"P1_037":("D","Restates the documented act - the head presented to Caesar: Plutarch, *Pompey* 77-80; Dio 42. Retagged from [V]: a host echo that restates a fact is still asserting it."),
"P1_038":("I","Interpretation of the court's miscalculation, consistent with the Roman reaction the sources record; the reading is hers."),
"P1_039":("D","The carpet is the popular modern version; the host states it as the received story, which is what it is."),
"P1_041":("D","Plutarch, *Life of Caesar* 49 - a bedding sack (στρωματόδεσμον), not a carpet. **A deliberate correction of a popular story - flag it in the description.**"),
"P1_043":("D","The siege of the palace quarter and the harbour fire: Caesar, *Civil War* 3.106ff; the *Alexandrian War*."),
"P1_044":("D","Caesar's force on arrival was roughly 3,200 legionaries with cavalry; the siege ran through the winter of 48-47 BC. VERIFY the four-month figure against the *Alexandrian War* before publication."),
"P1_045":("V",""),
"P1_046":("I","Modern scholarly consensus is that dockside warehouses and stored books burned in 48 BC and that the Library itself was not destroyed then; the ancient sources diverge. Roller; Chauveau. **A deliberate correction - flag it in the description.**"),
"P1_048":("D","Caesarion, born 47 BC and named for Caesar: Plutarch; Dio."),
"P1_049":("I","Motive. The actions are documented; the calculation behind them is reconstruction and is written as hers."),
"P1_051":("D","Her residence in Caesar's gardens across the Tiber, 46-44 BC: Cicero, *Letters to Atticus*."),
"P1_052":("D","She was in Rome at the assassination and left within weeks: Cicero, *Att.* 14."),
"P1_054":("V",""),
"P1_056":("I","'Egypt did not survive without me' - the Ptolemaic kingdom did end with her, which is documented; the claim of mutual dependency is her reading. Retagged from [V]."),
"P1_058":("D","Caesar's assassination, the fracturing of Rome, and the alliance with Antony from 41 BC: Plutarch, *Life of Antony*."),
"P1_059":("D","Antony's need for funds and an eastern base for the Parthian campaign: Plutarch, *Ant.*; Dio 49."),
"P1_061":("D","Three children - Alexander Helios, Cleopatra Selene, Ptolemy Philadelphus - and the public ceremony of 34 BC: Plutarch, *Ant.* 54; Dio 49.41."),
"P1_062":("D","The Donations of Alexandria, 34 BC: Plutarch, *Ant.* 54; Dio 49.41."),
"P1_063":("V",""),
"P1_064":("D","Presupposes that Octavian's later account diverged from what the ceremony granted, which is documented: Dio 50.1-5. Retagged from [V]."),
"P1_065":("D","Titles granted over Armenia, Media and Parthia - territory not held: Plutarch, *Ant.* 54; Dio 49.41."),
"P1_066":("V",""),
"P1_067":("I","Rhetorical analogy. Rome's early expansion as claimed before it was held is a defensible characterisation, offered as her argument rather than as a statement of record. Retagged from [V]."),
"P1_068":("D","Octavian's use of the Donations in the propaganda campaign at Rome: Dio 50.1-5."),
"P1_069":("I","Interpretation of Octavian's motive, well supported by the shape of the propaganda campaign the sources describe, but a reading rather than a statement."),
"P1_071":("D","Antony's marriage to Octavia, the divorce by letter and her removal from his house: Plutarch, *Ant.* 57."),
"P1_072":("I","The marriage as an instrument of the Treaty of Brundisium is the standard reading; the judgement that Rome understood it so is hers."),
"P1_073":("V",""),
"P1_074":("V",""),
"P1_076":("D","Octavian's seizure of Antony's will from the Vestals and its public reading, including the Alexandria burial request: Dio 50.3; Plutarch, *Ant.* 58."),
"P1_077":("I","The burial request is documented; that it was the unforgivable detail is her reading of the Roman reaction."),
"P1_079":("D","War was declared on Cleopatra, not on Antony: Dio 50.4-6."),
"P1_080":("I","That it remained a Roman civil war fought under a foreign name is the standard modern reading, stated here as hers."),
"P1_081":("D","Actium, 31 BC: Plutarch, *Ant.* 65-66; Dio 50.31-35."),
"P1_083":("D","Roughly sixty ships, her own squadron, breaking through and sailing south during the battle: Plutarch, *Ant.* 66; Dio 50.33."),
"P1_084":("D","Restates the documented withdrawal during the engagement: Plutarch, *Ant.* 66; Dio 50.33. Retagged from [V]."),
"P1_085":("D","Her repetition of the same documented fact, used for emphasis: Plutarch, *Ant.* 66; Dio 50.33. Retagged from [V]."),
"P1_087":("V",""),
"P1_088":("V",""),
"P1_089":("D","Antony and Cleopatra's association is the single best-known fact about her and the subject Part 2 opens on. The host's framing of what 'most people know' is a statement about reception, not about the record."),
"P1_092":("I","Rewritten line. The political basis of the Antony alliance is documented (Plutarch, *Ant.*; Dio 49); 'it was a treaty first' is her characterisation of it, not a source's words."),
}
