#!/usr/bin/env python3
"""
build_episode_cards.py — the last step of Mode 4.

    python3 build_episode_cards.py <Episodes/Guest>  [--part N] [--composite N]

    --part N  (default 1) reads P<N>_kit.md and card_data_p<N>.json. Part 1 keeps its original
              file names; Part 2+ renders carry a p<N> tag so nothing from Part 1 is overwritten.

By the time the production kit exists, every per-episode brand asset is already
decided inside it: §12 carries the lower-third names and the pull-quote lines
with the shot each lands over, the provenance tags carry the sources, and the
arc carries the next part's title. So none of it should be re-decided at the
edit — this renders all of it into the episode folder, ready to drop in.

Emits, into <Episodes/Guest>/:
    BRAND_endcard_p1.mp4 / .png     from card_data_p1.json
    BRAND_lowerthird_host.mov       alpha, from §12
    BRAND_lowerthird_guest.mov      alpha, from §12
    BRAND_pullquote_01..NN.mov      alpha, from §12
    BRAND_context_01..NN.mov/.webm  alpha, from §12 "Context cards" (who / where / what)
    BRAND_composite_p1.mp4          only with --composite N, eyewitness episodes
    CARD_PLACEMENTS.md              what goes where, for the edit

⚠️ The DESIGN of each of these is series-fixed and lives in Branding/intro_source/.
Only the render is per episode. Never write a render into Branding/.
"""
import os, sys, subprocess, json, re

HERE=os.path.dirname(os.path.abspath(__file__))
def run(*a):
    subprocess.run([sys.executable]+list(a),check=True)

def main():
    ep=os.path.abspath(sys.argv[1]).rstrip("/")
    comp=None
    if "--composite" in sys.argv: comp=sys.argv[sys.argv.index("--composite")+1]
    N=(sys.argv[sys.argv.index("--part")+1].lstrip("Pp") if "--part" in sys.argv else "1")
    PART=f"P{N}"; TAG="" if N=="1" else f"p{N}_"
    kit=os.path.join(ep,f"{PART}_kit.md")

    print("="*72); print("1. Sources audit — the card is a claim; check it against the tags")
    print("="*72)
    run(os.path.join(HERE,"sources_audit.py"), kit, os.path.join(ep,f"card_data_p{N}.json"))

    data=os.path.join(ep,f"card_data_p{N}.json")
    if not os.path.exists(data):
        json.dump({"sources":["[curate from the audit above]"],"next":"[next part title]"},
                  open(data,"w",encoding="utf-8"),indent=2,ensure_ascii=False)
        print(f"\n!! wrote a stub {os.path.basename(data)} — curate it, then re-run.\n")
        return

    print("\n"+"="*72); print("2. End card"); print("="*72)
    import tempfile   # frames outside the project: the bridge cannot delete inside it (was <ep>/_ecfr until 2026-09-23)
    fr=os.environ.get("ENDCARD_FRAMES") or tempfile.mkdtemp(prefix="ecfr_")
    run(os.path.join(HERE,"endcard_build.py"), data, fr)
    subprocess.run(["ffmpeg","-v","error","-r","24","-i",f"{fr}/f%04d.png","-c:v","libx264",
                    "-pix_fmt","yuv420p","-crf","23","-preset","slow","-movflags","+faststart",
                    os.path.join(ep,f"BRAND_endcard_p{N}.mp4"),"-y"],check=True)
    subprocess.run(["ffmpeg","-v","error","-i",f"{fr}/f0470.png",
                    os.path.join(ep,f"BRAND_endcard_p{N}.png"),"-y"],check=True)
    print(f"   BRAND_endcard_p{N}.mp4 + .png")

    if comp:
        print("\n"+"="*72); print(f"3. Composite card — {comp} first-hand accounts"); print("="*72)
        import tempfile
        cf=tempfile.mkdtemp(prefix="cofr_")
        run(os.path.join(HERE,"composite_build.py"), comp, cf)
        subprocess.run(["ffmpeg","-v","error","-r","24","-i",f"{cf}/f%03d.png","-c:v","libx264",
                        "-pix_fmt","yuv420p","-crf","20","-movflags","+faststart",
                        os.path.join(ep,f"BRAND_composite_p{N}.mp4"),"-y"],check=True)
        print(f"   BRAND_composite_p{N}.mp4")
    else:
        print("\n(no --composite: named-figure episode, no composite card)")

    print("\n"+"="*72); print("4. Lower thirds and pull-quotes"); print("="*72)
    run(os.path.join(HERE,"plates_build.py"), ep, "--part", N)

    print("\n"+"="*72); print("5. Context cards"); print("="*72)
    import context_build as cb
    ctx=cb.parse(kit) if "### Context cards" in open(kit,encoding="utf-8").read() else []
    for r in ctx:
        _o=os.path.join(ep,f"BRAND_context_{TAG}{int(r['n']):02d}.mov")
        if os.environ.get("RESUME") and os.path.exists(_o) and os.path.exists(_o[:-4]+".webm"): continue   # finish a long render across runs
        cb.mov(r["side"], r["label"], r["name"], r["gloss"], r["source"],
               os.path.join(ep,f"BRAND_context_{TAG}{int(r['n']):02d}.mov"), 5.5)
    if not ctx: print("   (no Context cards table in §12)")

    # placement note for the edit
    sys.path.insert(0,HERE)
    import plates_build as pb
    lower,quotes=pb.parse(kit)
    out=[ "# Card placements — generated by Mode 4. Do not invent these at the edit.\n",
          "\n## Lower thirds\n\n| file | opens over |\n|---|---|"]
    for l in lower: out.append(f"| `BRAND_lowerthird_{l['who'].lower()}.mov` | `{l['shot']}` |")
    out.append("\n## Pull-quotes\n\n| file | lands over | line |\n|---|---|---|")
    for i,q in enumerate(quotes,1):
        out.append(f"| `BRAND_pullquote_{TAG}{i:02d}.mov` | `{q['over']}` | \"{q['line']}\" |")
    out.append("\n## Context cards — enter AS THE WORD IS SAID, 5.5 s\n\n| file | over | on the word | side | name |\n|---|---|---|---|---|")
    for r in ctx:
        out.append(f"| `BRAND_context_{TAG}{int(r['n']):02d}.mov` | `{r['shot']}` | \"{r['word']}\" | {r['side']} | {r['name']} |")
    out.append("\n## Fixed furniture, same every episode\n")
    out.append("`BRAND_opening.mp4` at 0:00 · `BRAND_actbreak_vessel.mp4` then `_stone.mp4` at the two act "
               "breaks · `BRAND_subscribe.mov` once after a strong beat in Act B or C · "
               f"`BRAND_bumper_out` then `BRAND_endcard_p{N}.mp4` at the close.\n")
    open(os.path.join(ep,"CARD_PLACEMENTS.md" if N=="1" else f"CARD_PLACEMENTS_p{N}.md"),"w",encoding="utf-8").write("\n".join(out))
    print("\n   CARD_PLACEMENTS.md written")
    print("\nDone. Every per-episode brand asset is in", os.path.basename(ep))

if __name__=="__main__": main()
